# Generated by Django 5.2.4 on 2025-08-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_editora_livro_desconto_livro_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='endereco',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
    ]
