# Generated by Django 5.2.4 on 2025-09-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_editora_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.editora'),
            preserve_default=False,
        ),
    ]
