# Generated by Django 5.2.4 on 2025-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_livro_delete_bibliotecario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
    ]
