# Generated by Django 5.2.4 on 2025-08-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_livro_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editora', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='dimensoes',
            field=models.CharField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='estoque',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='idioma',
            field=models.CharField(default='Portugues'),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(default='sadas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(default='sdad', max_length=100),
            preserve_default=False,
        ),
    ]
