# Generated by Django 5.2.4 on 2025-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_editora_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
